### ISSUE TITLE
Avoid ivy dependency

### ISSUE THREAD

**Issue by purcell** [dingansichKum0/lacquer#3]
Hey, I saw this package appear in MELPA and I didn't provide a review before it got merged, but you should really fix the dependency on `ivy` -- there's absolutely no need for it, as far as I can tell: just use `completing-read`, and then the user's preferred completion system will kick in. It's important to avoid unrelated dependencies, not only because inconsistent behaviour when using this package would confuse users of other completion systems, but also because there's no reason for users to end up with a lot of bulky unnecessary installed packages. Hope this suggestion helps!

**Comment by zakudriver** [comment]
Thank you for your advice. I have corrected it.

**Comment by purcell** [comment]
Yay, nice!
