### ISSUE TITLE
lacquer and server mode

### ISSUE THREAD

**Issue by LevPetrovitch** [dingansichKum0/lacquer#4]
When Emacs is automatically started in server mode by means of systemd, executing `lacquer-auto-mode` in `after-init-hook`, as 
shown in the documentation, cause the startup process to stall without starting the daemon. The last message shown in the log is the one about successfully loading the selected theme, then is stops and nothing else happen. 

I found a workaround by adding `lacquer-auto-mode`   to the `server-after-make-frame-hook`. Obviously, doing so means that lacquer doesn't start anymore when I launch a standalone Emacs process. This in turn means that I need to keep two slightly different sets of startup files: one using  `server-after-make-frame-hook` to use in the environments (e.g. home) where I do 
use systemd to start Emacs and one using  `after-init-hook` for those where I do not (e.g. at work).

**Comment by LevPetrovitch** [comment]
I found a workaround. Maybe not the cleanest thing on earth, but it works. The idea is to add to `after-init-hook` the following function, instead of a plain `lacquer-auto-mode`
```
(lambda () (if (daemonp) 
		      (add-hook 'server-after-make-frame-hook #'lacquer-auto-mode)
		      (lacquer-auto-mode)))
```
If the original issue can't be solved, maybe adding this workaround to the documentation could help other people in my situation

**Comment by zakudriver** [comment]
Thank you for your advice. 
I'm not familiar enough with either emasc server or emacsclient. After few simple attempts,I found that you are right. I will add workaround to the document.
